/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UsuarioController;
import java.awt.Color;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import model.Usuario;
import sun.security.provider.VerificationProvider;

/**
 *
 * @author aluno.saolucas
 */
public class FrAlterarUsuario extends javax.swing.JDialog {

    private int pkUsuario;

    /**
     * Creates new form FrAlterarUsuario
     */
    public FrAlterarUsuario(java.awt.Frame parent, boolean modal, int pkUsuario) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        setPkusuario(pkUsuario);
        carregarUsuario();
    }

    public void setPkusuario(int pkUsuario) {
        this.pkUsuario = pkUsuario;
    }

    public void carregarUsuario() {

        UsuarioController controller = new UsuarioController();
        Usuario usuario = controller.buscarPorPk(pkUsuario);

        String codigo = String.valueOf(usuario.getPkUsuario());
        txtCodigo.setText(codigo);
        txtNome.setText(usuario.getNome());
        txtEmail.setText(usuario.getEmail());
        txtDataNasc.setText(utils.Utils.converterDateToString(usuario.getDataNasc()));
        chbAtivo.setSelected(usuario.getAtivo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        txtConfirmSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        chbAtivo = new javax.swing.JCheckBox();
        btnCancelar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        txtDataNasc = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAlterarSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        painel.setBackground(new java.awt.Color(78, 125, 184));
        painel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Alterar Usuário");
        painel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 15, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Código");
        painel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        txtCodigo.setEditable(false);
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        painel.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 340, 42));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Email");
        painel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));
        painel.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 337, 42));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Senha");
        painel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        txtSenha.setEditable(false);
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        painel.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 337, 42));

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Confirmar Senha ");
        painel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 30));

        txtConfirmSenha.setEditable(false);
        painel.add(txtConfirmSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 337, 40));

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Data de Nascimento");
        painel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, 30));

        chbAtivo.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        chbAtivo.setText("Ativo");
        chbAtivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAtivoActionPerformed(evt);
            }
        });
        painel.add(chbAtivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 119, 42));

        btnCancelar.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7853741_logout_kashifarif_exit_out_close_icon.png"))); // NOI18N
        btnCancelar.setText(" Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        painel.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, -1, -1));

        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/8666542_save_icon.png"))); // NOI18N
        btnSalvar.setText(" Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        painel.add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 194, -1));

        txtDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        txtDataNasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascActionPerformed(evt);
            }
        });
        painel.add(txtDataNasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 337, 40));
        painel.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 337, 42));

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nome");
        painel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        btnAlterarSenha.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        btnAlterarSenha.setText("Alterar Senha");
        btnAlterarSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarSenhaMouseClicked(evt);
            }
        });
        btnAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarSenhaActionPerformed(evt);
            }
        });
        painel.add(btnAlterarSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 320, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void chbAtivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAtivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbAtivoActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
        if(verificarCampos()){
            gravar();
        }
    }//GEN-LAST:event_btnSalvarMouseClicked

    public void gravar(){
        Usuario usuario = new Usuario();
        
        usuario.setPkUsuario(pkUsuario);
        usuario.setNome(txtNome.getText());
        usuario.setEmail(txtEmail.getText());
        
        if(txtSenha.isEditable()){
            String senha = new String(txtSenha.getPassword());
            String senhaHash = utils.Utils.calcularHash(senha);
            usuario.setSenha(senhaHash);
        }
        Date data = utils.Utils.converterStringToDate(txtDataNasc.getText());
        usuario.setDataNasc(data);
        
        usuario.setAtivo(chbAtivo.isSelected());
        
        UsuarioController controller = new UsuarioController();
        
        if(controller.alterarUsuario(usuario)){
            JOptionPane.showMessageDialog(null , "Usuário: " + usuario.getNome() + " alterado com sucesso !");
            this.dispose();
            
        }else{
            JOptionPane.showMessageDialog(null, "Usuário não alterado ! ");
        }
        
    }
    
    public boolean verificarCampos() {
        String CampNome = new String(txtNome.getText());
        String CampEmail = new String(txtEmail.getText());
        String CampData = new String(txtDataNasc.getText());
        String senha = new String(txtSenha.getPassword());
        String confirmSenha = new String(txtSenha.getPassword());
        String dataNascFormat = "\\d{2}/\\d{2}/\\d{4}";
        boolean dataNascVerificar = Pattern.matches(CampData, dataNascFormat);
        if (!CampNome.matches("[a-z A-Z]+")) {
            JOptionPane.showMessageDialog(null, "Erro");
            return false;

        }
        if (!CampEmail.matches("[a-zA-Z0-9._-]+@[a-zA-Z0-9]+.com")) {
            JOptionPane.showMessageDialog(null, "Erro");
            return false;
        }
        if(txtSenha.isEditable()){
            
            if (!(senha.length() > 6)) {
                JOptionPane.showMessageDialog(null, "Digite uma senha de pelos menos 6 digitos !");
                return false;
            }
            if (!senha.equals(confirmSenha)) {
                JOptionPane.showMessageDialog(null, "As senhas estão diferentes !");
                return false;
            }
        }

        if (!CampData.equals("")) {
            return true;
            
        }
        if (dataNascVerificar = false && !(CampData.equals("")) ) {
                JOptionPane.showMessageDialog(null, "Insira a data de nascimento seguindo o formato 00/00/0000");
            }

        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo Nome se encontra vazio !");
            return false;
        }
        if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo Email se encontra vazio !");
            return false;
        }

        if (txtSenha.getPassword().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo Senha se encontra vazio !");
            return false;
        }


        return true;
    }   
    private void txtDataNascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascActionPerformed

    private void btnAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarSenhaActionPerformed

    private void btnAlterarSenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarSenhaMouseClicked
        // TODO add your handling code here:
        if (txtSenha.isEditable() == false){
        txtSenha.setEditable(true);
        txtConfirmSenha.setEditable(true);
        txtSenha.setBackground(Color.white);
        txtConfirmSenha.setBackground(Color.white);
        btnAlterarSenha.setText("Cancelar alteração");
        txtSenha.setText("");
        txtConfirmSenha.setText("");
        }else {
            txtSenha.setEditable(false);
            txtConfirmSenha.setEditable(false);
            txtSenha.setBackground(Color.gray);                   
            txtConfirmSenha.setBackground(Color.gray);
            btnAlterarSenha.setText("Alterar Senha");
            txtSenha.setText(""); 
            txtConfirmSenha.setText("");
        }
    }//GEN-LAST:event_btnAlterarSenhaMouseClicked

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrAlterarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrAlterarUsuario dialog = new FrAlterarUsuario(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarSenha;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JCheckBox chbAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel painel;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JPasswordField txtConfirmSenha;
    private javax.swing.JFormattedTextField txtDataNasc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
